version: '3'
name: 'myproj'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - path.data=/usr/share/elasticsearch/data
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0  # Allow access from external IPs
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SERVER_NAME=my-kibana
      - XPACK_SECURITY_ENABLED=false
      - PATH_DATA=/usr/share/kibana/data
      - SERVER_HOST=0.0.0.0  # Allow Kibana to be accessed externally
    volumes:
      - ./kibana/data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
